// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: wire.proto

package grid

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WireClient is the client API for Wire service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WireClient interface {
	Process(ctx context.Context, in *Delivery, opts ...grpc.CallOption) (*Delivery, error)
}

type wireClient struct {
	cc grpc.ClientConnInterface
}

func NewWireClient(cc grpc.ClientConnInterface) WireClient {
	return &wireClient{cc}
}

func (c *wireClient) Process(ctx context.Context, in *Delivery, opts ...grpc.CallOption) (*Delivery, error) {
	out := new(Delivery)
	err := c.cc.Invoke(ctx, "/grid.Wire/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WireServer is the server API for Wire service.
// All implementations must embed UnimplementedWireServer
// for forward compatibility
type WireServer interface {
	Process(context.Context, *Delivery) (*Delivery, error)
	mustEmbedUnimplementedWireServer()
}

// UnimplementedWireServer must be embedded to have forward compatible implementations.
type UnimplementedWireServer struct {
}

func (UnimplementedWireServer) Process(context.Context, *Delivery) (*Delivery, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedWireServer) mustEmbedUnimplementedWireServer() {}

// UnsafeWireServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WireServer will
// result in compilation errors.
type UnsafeWireServer interface {
	mustEmbedUnimplementedWireServer()
}

func RegisterWireServer(s grpc.ServiceRegistrar, srv WireServer) {
	s.RegisterService(&Wire_ServiceDesc, srv)
}

func _Wire_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Delivery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grid.Wire/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServer).Process(ctx, req.(*Delivery))
	}
	return interceptor(ctx, in, info, handler)
}

// Wire_ServiceDesc is the grpc.ServiceDesc for Wire service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Wire_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grid.Wire",
	HandlerType: (*WireServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _Wire_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wire.proto",
}
