// Code generated by protoc-gen-go.
// source: protomessage.proto
// DO NOT EDIT!

/*
Package protomessage is a generated protocol buffer package.

It is generated from these files:
	protomessage.proto

It has these top-level messages:
	Person
*/
package protomessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_CELL Person_PhoneType = 0
	Person_HOME Person_PhoneType = 1
	Person_WORK Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "CELL",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"CELL": 0,
	"HOME": 1,
	"WORK": 2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Person struct {
	Name   string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email  string                `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Phones []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phones" json:"phones,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type Person_PhoneNumber struct {
	Number    string           `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	PhoneType Person_PhoneType `protobuf:"varint,2,opt,name=phoneType,enum=protomessage.Person_PhoneType" json:"phoneType,omitempty"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetPhoneType() Person_PhoneType {
	if m != nil {
		return m.PhoneType
	}
	return Person_CELL
}

func init() {
	proto.RegisterType((*Person)(nil), "protomessage.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "protomessage.Person.PhoneNumber")
	proto.RegisterEnum("protomessage.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

func init() { proto.RegisterFile("protomessage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x03, 0x73, 0x84, 0x78, 0x90, 0xc5, 0x94,
	0xfe, 0x30, 0x72, 0xb1, 0x05, 0xa4, 0x16, 0x15, 0xe7, 0xe7, 0x09, 0x09, 0x71, 0xb1, 0xe4, 0x25,
	0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac, 0xa9,
	0xb9, 0x89, 0x99, 0x39, 0x12, 0x4c, 0x60, 0x41, 0x08, 0x47, 0xc8, 0x82, 0x8b, 0xad, 0x20, 0x23,
	0x3f, 0x2f, 0xb5, 0x58, 0x82, 0x45, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x41, 0x0f, 0xc5, 0x1e, 0x88,
	0x79, 0x7a, 0x01, 0x20, 0x25, 0x7e, 0xa5, 0xb9, 0x49, 0xa9, 0x45, 0x41, 0x50, 0xf5, 0x52, 0xc9,
	0x5c, 0xdc, 0x48, 0xc2, 0x42, 0x62, 0x5c, 0x6c, 0x79, 0x60, 0x16, 0xd4, 0x52, 0x28, 0x4f, 0xc8,
	0x86, 0x8b, 0x13, 0xac, 0x21, 0xa4, 0xb2, 0x20, 0x15, 0x6c, 0x35, 0x9f, 0x91, 0x1c, 0x6e, 0x3b,
	0x40, 0xaa, 0x82, 0x10, 0x1a, 0x94, 0x34, 0xb9, 0x38, 0xe1, 0xe2, 0x42, 0x1c, 0x5c, 0x2c, 0xce,
	0xae, 0x3e, 0x3e, 0x02, 0x0c, 0x20, 0x96, 0x87, 0xbf, 0xaf, 0xab, 0x00, 0x23, 0x88, 0x15, 0xee,
	0x1f, 0xe4, 0x2d, 0xc0, 0x94, 0xc4, 0x06, 0x36, 0xd4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa4,
	0xa1, 0xae, 0x95, 0x29, 0x01, 0x00, 0x00,
}
