// Code generated by protoc-gen-go.
// source: msgs.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	msgs.proto

It has these top-level messages:
	Event
	EventResponse
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Event struct {
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	User      string `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Url       string `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EventResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *EventResponse) Reset()                    { *m = EventResponse{} }
func (m *EventResponse) String() string            { return proto.CompactTextString(m) }
func (*EventResponse) ProtoMessage()               {}
func (*EventResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Event)(nil), "main.Event")
	proto.RegisterType((*EventResponse)(nil), "main.EventResponse")
}

var fileDescriptor0 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x2d, 0x4e, 0x2f,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xf2, 0xe6, 0x62,
	0x75, 0x2d, 0x4b, 0xcd, 0x2b, 0x11, 0x92, 0xe1, 0xe2, 0x2c, 0xc9, 0xcc, 0x4d, 0x2d, 0x2e, 0x49,
	0xcc, 0x2d, 0x90, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x08, 0x08, 0x09, 0x71, 0xb1, 0x94,
	0x16, 0xa7, 0x16, 0x49, 0x30, 0x81, 0x25, 0xc0, 0x6c, 0x21, 0x01, 0x2e, 0xe6, 0xd2, 0xa2, 0x1c,
	0x09, 0x66, 0xb0, 0x10, 0x88, 0xa9, 0x24, 0xcf, 0xc5, 0x0b, 0x36, 0x2c, 0x28, 0xb5, 0xb8, 0x20,
	0x3f, 0xaf, 0x38, 0x55, 0x88, 0x8f, 0x8b, 0x29, 0x33, 0x05, 0x6a, 0x1a, 0x90, 0x95, 0xc4, 0x06,
	0xb6, 0xda, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x54, 0x4a, 0xf8, 0x88, 0x00, 0x00, 0x00,
}
