// Code generated by protoc-gen-go.
// source: wire.proto
// DO NOT EDIT!

/*
Package grid is a generated protocol buffer package.

It is generated from these files:
	wire.proto

It has these top-level messages:
	Delivery
*/
package grid

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Delivery_Ver int32

const (
	Delivery_V1 Delivery_Ver = 0
)

var Delivery_Ver_name = map[int32]string{
	0: "V1",
}
var Delivery_Ver_value = map[string]int32{
	"V1": 0,
}

func (x Delivery_Ver) String() string {
	return proto.EnumName(Delivery_Ver_name, int32(x))
}
func (Delivery_Ver) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Delivery_Enc int32

const (
	Delivery_Gob Delivery_Enc = 0
)

var Delivery_Enc_name = map[int32]string{
	0: "Gob",
}
var Delivery_Enc_value = map[string]int32{
	"Gob": 0,
}

func (x Delivery_Enc) String() string {
	return proto.EnumName(Delivery_Enc_name, int32(x))
}
func (Delivery_Enc) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

type Delivery struct {
	Ver      Delivery_Ver `protobuf:"varint,1,opt,name=ver,enum=grid.Delivery_Ver" json:"ver,omitempty"`
	Enc      Delivery_Enc `protobuf:"varint,2,opt,name=enc,enum=grid.Delivery_Enc" json:"enc,omitempty"`
	Data     []byte       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Receiver string       `protobuf:"bytes,4,opt,name=receiver" json:"receiver,omitempty"`
}

func (m *Delivery) Reset()                    { *m = Delivery{} }
func (m *Delivery) String() string            { return proto.CompactTextString(m) }
func (*Delivery) ProtoMessage()               {}
func (*Delivery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*Delivery)(nil), "grid.Delivery")
	proto.RegisterEnum("grid.Delivery_Ver", Delivery_Ver_name, Delivery_Ver_value)
	proto.RegisterEnum("grid.Delivery_Enc", Delivery_Enc_name, Delivery_Enc_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Wire service

type WireClient interface {
	Process(ctx context.Context, in *Delivery, opts ...grpc.CallOption) (*Delivery, error)
}

type wireClient struct {
	cc *grpc.ClientConn
}

func NewWireClient(cc *grpc.ClientConn) WireClient {
	return &wireClient{cc}
}

func (c *wireClient) Process(ctx context.Context, in *Delivery, opts ...grpc.CallOption) (*Delivery, error) {
	out := new(Delivery)
	err := grpc.Invoke(ctx, "/grid.wire/Process", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Wire service

type WireServer interface {
	Process(context.Context, *Delivery) (*Delivery, error)
}

func RegisterWireServer(s *grpc.Server, srv WireServer) {
	s.RegisterService(&_Wire_serviceDesc, srv)
}

func _Wire_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Delivery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grid.wire/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServer).Process(ctx, req.(*Delivery))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wire_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grid.wire",
	HandlerType: (*WireServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _Wire_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wire.proto",
}

func init() { proto.RegisterFile("wire.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x8f, 0xc1, 0x4a, 0x86, 0x40,
	0x10, 0x80, 0xdd, 0x7f, 0x17, 0xb5, 0xa1, 0x44, 0xe6, 0xb4, 0x78, 0x92, 0xa5, 0x83, 0x10, 0x2c,
	0xa4, 0xaf, 0x90, 0x74, 0x8d, 0x3d, 0x78, 0xd7, 0x75, 0x08, 0x21, 0xdc, 0x18, 0xc5, 0xe8, 0x81,
	0x7a, 0xcf, 0x58, 0xa1, 0xa0, 0xf8, 0x6f, 0xf3, 0xf1, 0x7d, 0x30, 0x33, 0x00, 0x1f, 0x0b, 0x93,
	0x7d, 0xe7, 0xb0, 0x07, 0x54, 0xaf, 0xbc, 0xcc, 0xe6, 0x4b, 0x40, 0xfe, 0x44, 0x6f, 0xcb, 0x41,
	0xfc, 0x89, 0xf7, 0x20, 0x0f, 0x62, 0x2d, 0x6a, 0xd1, 0x14, 0x2d, 0xda, 0x18, 0xd8, 0x1f, 0x69,
	0x07, 0x62, 0x17, 0x75, 0xac, 0x68, 0xf5, 0xfa, 0x72, 0xb5, 0xea, 0x57, 0xef, 0xa2, 0x46, 0x04,
	0x35, 0x8f, 0xfb, 0xa8, 0x65, 0x2d, 0x9a, 0x5b, 0x77, 0xce, 0x58, 0x41, 0xce, 0xe4, 0x29, 0x96,
	0x5a, 0xd5, 0xa2, 0xb9, 0x71, 0xbf, 0x6c, 0xee, 0x40, 0x0e, 0xc4, 0x98, 0xc2, 0x65, 0x78, 0x2c,
	0x13, 0x53, 0x80, 0xec, 0x57, 0x8f, 0x19, 0xc8, 0xe7, 0x30, 0x95, 0x49, 0xdb, 0x81, 0x8a, 0xb7,
	0xe3, 0x03, 0x64, 0x2f, 0x1c, 0x3c, 0x6d, 0x1b, 0x16, 0x7f, 0x57, 0x57, 0xff, 0xd8, 0x24, 0x53,
	0x7a, 0x7e, 0xda, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x21, 0x05, 0xca, 0xf7, 0x00, 0x00,
	0x00,
}
