on: push
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.x.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    name: Go ${{ matrix.go-version }} (${{ matrix.platform }})
    services:
      etcd:
        image: quay.io/coreos/etcd:v3.5.0
        env:
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
          ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
        ports:
          - 127.0.0.1:2379:2379
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test
      run: go test -race -timeout 360s -v ./...
